const Jadwal = [
  {
    jadwal_id: '001',
    pelabuhan_awal: 'Jakarta',
    pelabuhan_tujuan: 'Bandung',
    kelas_layanan: 'Eksekutif',
    harga: 'Rp. 1.100.000',
    kuota: '100',
  },
  {
    jadwal_id: '002',
    pelabuhan_awal: 'Bandung',
    pelabuhan_tujuan: 'Jakarta',
    kelas_layanan: 'Eksekutif',
    harga: 'Rp. 1.300.000',
    kuota: '110',
  },
  {
    jadwal_id: '003',
    pelabuhan_awal: 'Makassar',
    pelabuhan_tujuan: 'Banten',
    kelas_layanan: 'Eksekutif',
    harga: 'Rp. 1.800.000',
    kuota: '180',
  },
  {
    jadwal_id: '004',
    pelabuhan_awal: 'Banten',
    pelabuhan_tujuan: 'Makassar',
    kelas_layanan: 'Eksekutif',
    harga: 'Rp. 1.700.000',
    kuota: '160',
  },
  {
    jadwal_id: '005',
    pelabuhan_awal: 'Bali',
    pelabuhan_tujuan: 'Merak',
    kelas_layanan: 'Eksekutif',
    harga: 'Rp. 1.400.000',
    kuota: '130',
  },
  {
    jadwal_id: '006',
    pelabuhan_awal: 'Merak',
    pelabuhan_tujuan: 'Bali',
    kelas_layanan: 'Eksekutif',
    harga: 'Rp. 1.000.000',
    kuota: '100',
  },
  {
    jadwal_id: '007',
    pelabuhan_awal: 'Jakarta',
    pelabuhan_tujuan: 'Bandung',
    kelas_layanan: 'Ekonomi',
    harga: 'Rp. 500.000',
    kuota: '50',
  },
  {
    jadwal_id: '008',
    pelabuhan_awal: 'Bandung',
    pelabuhan_tujuan: 'Jakarta',
    kelas_layanan: 'Ekonomi',
    harga: 'Rp. 510.000',
    kuota: '51',
  },
  {
    jadwal_id: '009',
    pelabuhan_awal: 'Makassar',
    pelabuhan_tujuan: 'Banten',
    kelas_layanan: 'Ekonomi',
    harga: 'Rp. 520.000',
    kuota: '52',
  },
  {
    jadwal_id: '010',
    pelabuhan_awal: 'Banten',
    pelabuhan_tujuan: 'Makassar',
    kelas_layanan: 'Ekonomi',
    harga: 'Rp. 400.000',
    kuota: '30',
  },
  {
    jadwal_id: '011',
    pelabuhan_awal: 'Bali',
    pelabuhan_tujuan: 'Merak',
    kelas_layanan: 'Ekonomi',
    harga: 'Rp. 200.000',
    kuota: '59',
  },
  {
    jadwal_id: '012',
    pelabuhan_awal: 'Merak',
    pelabuhan_tujuan: 'Bali',
    kelas_layanan: 'Ekonomi',
    harga: 'Rp. 300.000',
    kuota: '40',
  },

  {
    jadwal_id: '013',
    pelabuhan_awal: 'Jakarta',
    pelabuhan_tujuan: 'Bali',
    kelas_layanan: 'Ekonomi',
    harga: 'Rp. 300.000',
    kuota: '40',
  },
];

export {Jadwal};
